# This is a config for E2B sandbox template.
# You can use template ID (s49iy3jbug34hd9xhyvc) or template name (vibe-nextjs-t3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-t3") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-t3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-t3')

team_id = "3282457c-4d2b-4595-a161-d085df9b56a7"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-t3"
template_id = "s49iy3jbug34hd9xhyvc"
